# Copyright (c) Helio Chissini de Castro, 2023. Part of the SW360 Frontend Project.
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
# License-Filename: LICENSE

name: Commit Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Validade Pull Request Commits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: webiny/action-conventional-commits@v1.1.0
      - uses: apache/skywalking-eyes/header@main

      - name: Check deny listed files
        run: bash .github/deny_list.sh
